Resources:
  AccessEKS:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - "eks.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonEKSClusterPolicy

  MyEKSCluster:
    Type: AWS::EKS::Cluster
    Properties:
      ResourcesVpcConfig:
        SubnetIds:
          - subnet-dfa5d4f4
          - subnet-0fdfd744
          - subnet-28807975
          - subnet-194da261
      RoleArn: !GetAtt AccessEKS.Arn
